// <auto-generated />
using IdServer4Demo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdServer4Demo.Data.Migrations.IdentityServer.ApplicationDb
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200319131536_InitialIdentityServerLoginDbMigration")]
    partial class InitialIdentityServerLoginDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("IdServer4Demo.Models.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserPassword")
                        .HasColumnName("UserPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserUid")
                        .HasColumnName("UserUid")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
